add buttons & it's propertyies
js-tasks-ru/htmlcss-20220120_vitalauto1980 pull request #3
Opened 2022-01-25 19:11 UTC by Vitalauto

2022-01-25 19:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-25 21:54 UTC, GSemikozov requested changes

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button {
в БЭМ блоки оформляем только классами, в нашем случае это .btn

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
не хватает еще font-family

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin-bottom: 14px;
марджины на уровне блока не задаем, это будет ошибкой)

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin-bottom: 14px;
зато не хватает внутренних отступов

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_primary, .btn__primary_disabled {
здесь и ниже - классы для изменения состояния кнопки в disabled (.btn__primary_disabled) будут лишними - это состояние будет одинаковым для всех типов кнопок, поэтому можно задать общий модификатор .btn_disabled

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
транзишны можно задать сразу на уровне блока

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn__primary_disabled, .btn__secondary_disabled, .btn__alternate_disabled {
вот вместо всего этого один класс .btn_disabled

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лучше заменить на pointer-events: none

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid #212429;
можно менять только цвет границы - border-color

2022-01-25 21:54 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <button class="btn__primary_disabled">Primary disabled</button>
btn__primary_disabled -> class="btn btn_primary btn_disabled"

2022-01-26 13:35 UTC, Vitalauto commented on 03-lection1/01-button/index.html
> +            <button class="btn__primary_disabled">Primary disabled</button>
сделано

2022-01-26 13:35 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    border: 1px solid #212429;
сделано

2022-01-26 13:36 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    cursor: default;
сделано, понята разница

2022-01-26 13:36 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +.btn__primary_disabled, .btn__secondary_disabled, .btn__alternate_disabled {
сделано

2022-01-26 13:36 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
сделано

2022-01-26 13:37 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +.btn_primary, .btn__primary_disabled {
сделано

2022-01-26 13:43 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    margin-bottom: 14px;
сделано

2022-01-26 13:43 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +button {
сделано

2022-01-26 13:44 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
Font- family прописан в подключённом файле main.css

2022-01-26 14:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 12:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-27 22:11 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
дело в том, что в проекте у нас будет использоваться два других шрифта, и если кнопка будет встроена в другой блок, в котором основным шрифтом будет не Roboto - то тогда мы отнаследуемся не от того шрифта от которого надо

2022-01-27 22:15 UTC, GSemikozov requested changes

2022-01-27 22:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px 0;
слева и справа тоже потребуется (на случай если текст будет длиннее ширины кнопки; кстати, советовал бы и ширину жестко не фиксировать, пусть бы определялась внутренним содержимым)

2022-01-27 22:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid;
вот здесь раз уж используем сокращенную запись - тогда нет смысла отдельно писать border-color, пусть будет border: 1px solid #acb5bd; Менять я имел в виду только на ховере (ведь при наведении мы меняет только цвет бордера, ширину бордера или стиль бордера мы не меняем)

2022-01-27 22:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid ;
это лишнее

2022-01-28 11:46 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
сделано

2022-01-28 11:50 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    border: 1px solid;
сделано

2022-01-28 11:50 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    border: 1px solid ;
есть

2022-01-28 12:01 UTC, Vitalauto commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px 0;
сделано

2022-01-28 12:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-29 18:50 UTC, GSemikozov approved these changes

2022-01-29 18:50 UTC, merged