skeleton
js-tasks-ru/htmlcss-20220120_vitalauto1980 pull request #5
Opened 2022-01-31 08:17 UTC by Vitalauto

2022-01-31 08:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-04 20:00 UTC, GSemikozov requested changes

2022-02-04 20:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	width: 172px;
тут - в процентах

2022-02-04 20:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	width: 257px;
и тут

2022-02-08 12:30 UTC, GSemikozov approved these changes

2022-02-08 12:30 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-08 12:31 UTC, GSemikozov approved these changes

2022-02-08 12:31 UTC, merged