add modal solution
js-tasks-ru/htmlcss-20220120_vitalauto1980 pull request #8
Opened 2022-02-08 18:07 UTC by Vitalauto

2022-02-08 18:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 21:57 UTC, GSemikozov requested changes

2022-02-08 21:57 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
компонент Кнопка у нас уже есть, поэтому - стили компонента надо просто подключить на страницу

2022-02-09 07:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-09 07:43 UTC, Vitalauto commented on 05-lection3/02-modal/modal.css
> +.button {
done

2022-02-09 19:13 UTC, GSemikozov approved these changes, later dismissed

2022-02-09 19:13 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-10 14:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-10 15:01 UTC, GSemikozov approved these changes

2022-02-10 15:01 UTC, merged